server:
  port: 8080 #Tomcat端口
  servlet:
    context-path: /dubbo-provider
application:
  version: 1.0.0
spring:
  profiles:
    active: @env@
  dubbo:
    application:
      name: dubbo-provider
    registry:
      address: zookeeper://java.zk2.51talk.com:2181?backup=java.zk1.51talk.com:2181,java.zk3.51talk.com:2181 #zookeeper地址
    protocol:
      name: dubbo
      port: 20890 #dubbo服务暴露的端口
    scan: com.talkplatform.dubbo.provider.impl

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.talkplatform.dubbo.entity

spring.datasource.course:
  url: jdbc:mysql://${jdbc.course.db}?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
  username: ${jdbc.course.username}
  password: ${jdbc.course.password}

spring.datasource.course.write:
  url: jdbc:mysql://${jdbc.course.write.db}?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
  username: ${jdbc.course.write.username}
  password: ${jdbc.course.write.password}

spring.datasource.textbook:
  url: jdbc:mysql://${jdbc.textbook.db}?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
  username: ${jdbc.textbook.username}
  password: ${jdbc.textbook.password}

